<?php

define('STATES', [
    '' => 'Unknown',
    'AL' => 'Alabama',
    'AK' => 'Alaska',
    'AZ' => 'Arizona',
    'AR' => 'Arkansas',
    'CA' => 'California',
    'CO' => 'Colorado',
    'CT' => 'Connecticut',
    'DE' => 'Delaware',
    'DC' => 'District of Columbia',
    'FL' => 'Florida',
    'GA' => 'Georgia',
    'HI' => 'Hawaii',
    'ID' => 'Idaho',
    'IL' => 'Illinois',
    'IN' => 'Indiana',
    'IA' => 'Iowa',
    'KS' => 'Kansas',
    'KY' => 'Kentucky',
    'LA' => 'Louisiana',
    'ME' => 'Maine',
    'MD' => 'Maryland',
    'MA' => 'Massachusetts',
    'MI' => 'Michigan',
    'MN' => 'Minnesota',
    'MS' => 'Mississippi',
    'MO' => 'Missouri',
    'MT' => 'Montana',
    'NE' => 'Nebraska',
    'NV' => 'Nevada',
    'NH' => 'New Hampshire',
    'NJ' => 'New Jersey',
    'NM' => 'New Mexico',
    'NY' => 'New York',
    'NC' => 'North Carolina',
    'ND' => 'North Dakota',
    'OH' => 'Ohio',
    'OK' => 'Oklahoma',
    'OR' => 'Oregon',
    'PA' => 'Pennsylvania',
    'RI' => 'Rhode Island',
    'SC' => 'South Carolina',
    'SD' => 'South Dakota',
    'TN' => 'Tennessee',
    'TX' => 'Texas',
    'UT' => 'Utah',
    'VT' => 'Vermont',
    'VA' => 'Virginia',
    'WA' => 'Washington',
    'WV' => 'West Virginia',
    'WI' => 'Wisconsin',
    'WY' => 'Wyoming',
]);
define('GENRES', [
    'blues',
    'classic rock',
    'country',
    'dance',
    'disco',
    'funk',
    'grunge',
    'hip-hop',
    'jazz',
    'metal',
    'new age',
    'oldies',
    'other',
    'pop',
    'r&b',
    'rap',
    'reggae',
    'rock',
    'techno',
    'industrial',
    'alternative',
    'ska',
    'death metal',
    'pranks',
    'soundtrack',
    'euro-techno',
    'ambient',
    'trip-hop',
    'vocal',
    'jazz+funk',
    'fusion',
    'trance',
    'classical',
    'instrumental',
    'acid',
    'house',
    'game',
    'sound clip',
    'gospel',
    'noise',
    'alternative rock',
    'bass',
    'soul',
    'punk',
    'space',
    'meditative',
    'instrumental pop',
    'instrumental rock',
    'ethnic',
    'gothic',
    'darkwave',
    'techno-industrial',
    'electronic',
    'pop-folk',
    'eurodance',
    'dream',
    'southern rock',
    'comedy',
    'cult',
    'gangsta',
    'top ',
    'christian rap',
    'pop/funk',
    'jungle',
    'native us',
    'cabaret',
    'new wave',
    'psychadelic',
    'rave',
    'showtunes',
    'trailer',
    'lo-fi',
    'tribal',
    'acid punk',
    'acid jazz',
    'polka',
    'retro',
    'musical',
    'rock & roll',
    'hard rock',
    'folk',
    'folk-rock',
    'national folk',
    'swing',
    'fast fusion',
    'bebob',
    'latin',
    'revival',
    'celtic',
    'bluegrass',
    'avantgarde',
    'gothic rock',
    'progressive rock',
    'psychedelic rock',
    'symphonic rock',
    'slow rock',
    'big band',
    'chorus',
    'easy listening',
    'acoustic',
    'humour',
    'speech',
    'chanson',
    'opera',
    'chamber music',
    'sonata',
    'symphony',
    'booty bass',
    'primus',
    'porn groove',
    'satire',
    'slow jam',
    'club',
    'tango',
    'samba',
    'folklore',
    'ballad',
    'power ballad',
    'rhythmic soul',
    'freestyle',
    'duet',
    'punk rock',
    'drum solo',
    'acapella',
    'euro-house',
    'dance hall',
    'goa',
    'drum & bass',
    'club \'house',
    'hardcore',
    'terror',
    'indie',
    'britpop',
    'negerpunk',
    'polsk punk',
    'beat',
    'christian gangsta rap',
    'heavy metal',
    'black metal',
    'crossover',
    'contemporary christian',
    'christian rock',
    'merengue',
    'salsa',
    'thrash metal',
    'anime',
    'jpop',
    'synthpop',
    'unknown']);